# Generated by Django 4.2.7 on 2024-02-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisinformationTacticModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField()),
                ('average_difficulty', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('disinformation_tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.disinformationtacticmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OptionSelectionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('information', models.TextField()),
                ('source', models.TextField()),
                ('correct_option', models.TextField()),
                ('incorrect_option', models.TextField()),
                ('display_not_sure', models.BooleanField()),
                ('feedback', models.TextField()),
                ('real_difficulty', models.IntegerField()),
                ('opportunity_cost', models.IntegerField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TacticExplainationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('explaination', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('disinformation_tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.disinformationtacticmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSelectionTacticModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('disinformation_tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.disinformationtacticmodel')),
                ('option_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.optionselectionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSelectionLessonModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.lessonmodel')),
                ('option_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.optionselectionmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='optionselectiontacticmodel',
            constraint=models.UniqueConstraint(fields=('option_selection', 'disinformation_tactic'), name='option_selection_tactic'),
        ),
        migrations.AddConstraint(
            model_name='optionselectionlessonmodel',
            constraint=models.UniqueConstraint(fields=('lesson', 'option_selection'), name='lesson_option_selection'),
        ),
        migrations.AddConstraint(
            model_name='lessonmodel',
            constraint=models.UniqueConstraint(fields=('user', 'disinformation_tactic', 'lesson_id'), name='user_tactic_lesson'),
        ),
    ]
