# Generated by Django 4.2.7 on 2023-12-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0002_lessonmodel_lessonmodel_lesson_primary_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticExplainationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('explaination', models.TextField()),
                ('disinformation_tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.disinformationtacticmodel')),
            ],
        ),
    ]
