# Generated by Django 4.2.7 on 2023-12-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0003_tacticexplainationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSelectionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('information', models.TextField()),
                ('correct_option', models.CharField(max_length=256)),
                ('incorrect_option', models.CharField(max_length=256)),
                ('display_not_sure', models.BooleanField()),
                ('decieved_feedback', models.TextField()),
                ('skepical_feedback', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
