# Generated by Django 4.2.7 on 2023-12-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0004_optionselectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSelectionTacticModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='lessonmodel',
            name='lesson_primary_key',
        ),
        migrations.AddConstraint(
            model_name='lessonmodel',
            constraint=models.UniqueConstraint(fields=('user', 'disinformation_tactic', 'lesson_id'), name='user_tactic_lesson'),
        ),
        migrations.AddField(
            model_name='optionselectiontacticmodel',
            name='option_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.optionselectionmodel'),
        ),
        migrations.AddField(
            model_name='optionselectiontacticmodel',
            name='tactic_explaination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.tacticexplainationmodel'),
        ),
        migrations.AddConstraint(
            model_name='optionselectiontacticmodel',
            constraint=models.UniqueConstraint(fields=('option_selection', 'tactic_explaination'), name='option_selection_tactic'),
        ),
    ]
