# Generated by Django 4.2.7 on 2024-01-05 17:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0005_optionselectiontacticmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonmodel',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='optionselectionmodel',
            old_name='date_created',
            new_name='created',
        ),
        migrations.AddField(
            model_name='disinformationtacticmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disinformationtacticmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='optionselectionmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='optionselectiontacticmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 5, 17, 42, 27, 798947, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionselectiontacticmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tacticexplainationmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tacticexplainationmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
