# Generated by Django 4.2.7 on 2024-01-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0006_rename_date_created_lessonmodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionselectionmodel',
            name='correct_option',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='optionselectionmodel',
            name='incorrect_option',
            field=models.TextField(),
        ),
    ]
