# Generated by Django 4.2.7 on 2024-01-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0007_alter_optionselectionmodel_correct_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionselectionmodel',
            old_name='decieved_feedback',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='optionselectionmodel',
            name='skepical_feedback',
        ),
    ]
