# Generated by Django 4.2.7 on 2024-01-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0009_inoculateuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='disinformationtacticmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disinformationtacticmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
