# Generated by Django 4.2.7 on 2024-01-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0010_disinformationtacticmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disinformationtacticmodel',
            name='description',
            field=models.TextField(default='A short description of the disinformation tactic'),
            preserve_default=False,
        ),
    ]
