# Generated by Django 4.2.7 on 2024-02-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0011_disinformationtacticmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionselectionmodel',
            name='opportunity_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionselectionmodel',
            name='real_difficulty',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
