# Generated by Django 4.2.7 on 2024-02-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0012_optionselectionmodel_opportunity_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='average_difficulty',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
