# Generated by Django 4.2.7 on 2024-02-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0013_lessonmodel_average_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='OptionSelectionLessonModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.lessonmodel')),
                ('option_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prebunkapi.optionselectionmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='optionselectionlessonmodel',
            constraint=models.UniqueConstraint(fields=('lesson', 'option_selection'), name='lesson_option_selection'),
        ),
    ]
