# Generated by Django 4.2.7 on 2024-02-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prebunkapi', '0014_lessonmodel_score_optionselectionlessonmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionselectionmodel',
            name='source_url',
            field=models.URLField(default='n/a'),
            preserve_default=False,
        ),
    ]
