stages:
  - deploy

deploy_django:
  stage: deploy
  tags:
    - deployer
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
  script:
    - echo "Running main script..."
    - cd /home/prebunker/
    - echo "Activating python virtual environment..."
    - source venv/bin/activate
    - echo "Pulling latest changes..."
    - cd /home/prebunker/FakeNewsInoculationGame/prebunk && git pull
    - echo "Updating python dependencies..."
    - pip install -r requirements.txt
    - echo "Migrating the Django database..."
    - python3 manage.py migrate && python3 manage.py collectstatic --noinput
    - echo "Restarting the prebunk server..."
    - sudo systemctl restart prebunk_game
    - echo "Done!"
