stages:
  - deploy

deploy_django:
  stage: deploy
  tags:
    - deployer
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
  script:
    - 'echo "Running main script..."'
    - cd /home/prebunker/ && source venv/bin/activate && cd /home/prebunker/FakeNewsInoculationGame/prebunk && git pull && pip install -r requirements.txt && python3 manage.py migrate && python3 manage.py collectstatic --noinput && sudo systemctl restart prebunk_game
